<a href="https://colab.research.google.com/github/Danilrox/Algebra-Lineal/blob/main/Tarea_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import datetime
import pytz # Import the pytz library for timezone handling

# Replace "Your Name" with your actual name
name = "Jose Daniel Maldonado Rodriguez"
carrera = "Computación - Primer ciclo"
# Get the timezone for Ecuador
ecuador_timezone = pytz.timezone('America/Guayaquil')
now_ecuador = datetime.datetime.now(ecuador_timezone)


print(f"Nombre: {name}")
print(f"Carrera: {carrera}")
print(f"Fecha: {now_ecuador.strftime('%Y-%m-%d')}")
print(f"Hora: {now_ecuador.strftime('%H:%M:%S')}")

Nombre: Jose Daniel Maldonado Rodriguez
Carrera: Computación - Primer ciclo
Fecha: 2025-10-23
Hora: 20:20:40


In [ ]:
import numpy as np

# Definir dos matrices A y B de 3x3
A = np.array([[2, 4, 6],
              [1, 3, 5],
              [0, -1, 2]])

B = np.array([[3, 2, 1],
              [4, 0, -2,],
              [1, 3, 5,]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
# Suma de matrices
# ------------------------------
suma = A + B
print("\n Suma (A + B):\n", suma)

# ------------------------------
#  Resta de matrices
# ------------------------------
resta = A - B
print("\n Resta (A - B):\n", resta)

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
escalar = 2
producto_escalar = escalar * A
print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
producto = np.dot(A, B)   # o A @ B
print("\n Producto matricial (A * B):\n", producto)

valor=(A[0,0] * B[0,2] + A[0,1] * B[1,2]+ A[0,2] * B[2,2])

print("El producto de C[0,0] es ",valor)

# ------------------------------
# Matriz transpuesta
# ------------------------------
#transpuesta = A.T
#print("\n Transpuesta de A (Aᵀ):\n", transpuesta)

Matriz A:
 [[ 2  4  6]
 [ 1  3  5]
 [ 0 -1  2]]

Matriz B:
 [[ 3  2  1]
 [ 4  0 -2]
 [ 1  3  5]]

 Suma (A + B):
 [[5 6 7]
 [5 3 3]
 [1 2 7]]

 Resta (A - B):
 [[-1  2  5]
 [-3  3  7]
 [-1 -4 -3]]

 Multiplicación por escalar (2 * A):
 [[ 4  8 12]
 [ 2  6 10]
 [ 0 -2  4]]

 Producto matricial (A * B):
 [[28 22 24]
 [20 17 20]
 [-2  6 12]]
El producto de C[0,0] es  24
